export const commentConstants = {
  POSTS_REQUEST: "POSTS_REQUEST",
  POSTS_SUCCESS: "POSTS_SUCCESS",
  POSTS_FAILURE: "POSTS_FAILURE",

  FETCH_COMMENTS_REQUEST: "FETCH_COMMENTS_REQUEST",
  FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
  FETCH_COMMENTS_FAILURE: "FETCH_COMMENTS_FAILURE",

  POST_DELETE_REQUEST: "POSTS_DELETE_REQUEST",
  POST_DELETE_SUCCESS: "POSTS_DELETE_SUCCESS",
  POST_DELETE_FAILURE: "POSTS_DELETE_FAILURE",

  INIT_REPLY_COMMENT: "INIT_REPLY_COMMENT",
  ADD_REPLY_COMMENT_SUCCESS: "ADD_REPLY_COMMENT_SUCCESS",
  ADD_REPLY_COMMENT_FAILURE: "ADD_REPLY_COMMENT_FAILURE",

  FETCH_COMMENT_REPLIES_REQUEST: "FETCH_COMMENT_REPLIES_REQUEST",
  FETCH_COMMENT_REPLIES_SUCCESS: "FETCH_COMMENT_REPLIES_SUCCESS",
  FETCH_COMMENT_REPLIES_FAILURE: "FETCH_COMMENT_REPLIES_FAILURE",

  INCREASE_REPLIES_NUMBER: "INCREASE_REPLIES_NUMBER",

  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",

  DISLIKE_COMMENT: "DISLIKE_COMMENT",
  LIKE_COMMENT: "LIKE_COMMENT",

  LIKE_COMMENT_REPLY: "LIKE_COMMENT_REPLY",
  DISLIKE_COMMENT_REPLY: "DISLIKE_COMMENT_REPLY",

  NEW_POST: "NEW_POST",
  GET_COMMENT_LIKES: "GET_COMMENT_LIKES",
  GET_COMMENT_REPLY_LIKES: "GET_COMMENT_REPLY_LIKES"
};
