export const notificationConstants = {
  TOGGLE_NOTIFICATION_POPUP: "TOGGLE_NOTIFICATION_POPUP",
  CLOSE_NOTIFICATION_POPUP: "CLOSE_NOTIFICATION_POPUP",
  ADD_NOTIFICATION: "ADD_NOTIFICATION",
  READ_NOTIFICATIOS: "READ_NOTIFICATIOS",
  FETCH_NOTIFICATIONS_REQUEST: "FETCH_NOTIFICATIONS_REQUEST",
  FETCH_NOTIFICATIONS_SUCCESS: "FETCH_NOTIFICATIONS_SUCCESS"
};
