export const postConstants = {
  POSTS_REQUEST: "POSTS_REQUEST",
  POSTS_SUCCESS: "POSTS_SUCCESS",
  POSTS_FAILURE: "POSTS_FAILURE",

  HASHTAG_POSTS_SUCCESS: "HASHTAG_POSTS_SUCCESS",
  LOCATION_POSTS_SUCCESS: "LOCATION_POSTS_SUCCESS",

  HASHTAG_POSTS_REQUEST: "HASHTAG_POSTS_REQUEST",
  LOCATION_POSTS_REQUEST: "LOCATION_POSTS_REQUEST",

  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",

  POST_DELETE_REQUEST: "POSTS_DELETE_REQUEST",
  POST_DELETE_SUCCESS: "POSTS_DELETE_SUCCESS",
  POST_DELETE_FAILURE: "POSTS_DELETE_FAILURE",

  LIKE_POST: "LIKE_POST",
  DISLIKE_POST: "DISLIKE_POST",

  GET_POST_LIKES: "GET_POST_LIKES",

  INIT_COMMENT: "INIT_COMMENT",

  NEW_POST: "NEW_POST",
  GET_POST: "GET_POST",

  //edit post page
  IMAGE_CROP_SELECT: "IMAGE_CROP_SELECT",
  IMAGE_SELECT: "IMAGE_SELECT",
  MAP_LOCATION_SELECT: "MAP_LOCATION_SELECT",
  CANVAS_HAS_VALUE: "CANVAS_HAS_VALUE"
  //-----------
};
