module.exports = {
  GET_USER: "GET_USER",

  DELETE_FIRST_NAME: "DELETE_FIRST_NAME",
  DELETE_LAST_NAME: "DELETE_LAST_NAME",
  DELETE_USERNAME: "DELETE_USERNAME",
  DELETE_EMAIL: "DELETE_EMAIL",
  DELETE_PASSWORD: "DELETE_PASSWORD",
  DELETE_RETYPE_PASSWORD: "DELETE_RETYPE_PASSWORD",

  EMPTY_FIRST_NAME: "EMPTY_FIRST_NAME",
  EMPTY_LAST_NAME: "EMPTY_LAST_NAME",
  EMPTY_USERNAME: "EMPTY_USERNAME",
  EMPTY_EMAIL: "EMPTY_EMAIL",
  EMPTY_PASSWORD: "EMPTY_PASSWORD",
  EMPTY_RETYPE_PASSWORD: "EMPTY_RETYPE_PASSWORD",

  TOOLONG_FIRST_NAME: "TOOLONG_FIRST_NAME",
  TOOLONG_LAST_NAME: "TOOLONG_LAST_NAME",
  TOOLONG_USERNAME: "TOOLONG_USERNAME",
  TOOLONG_EMAIL: "TOOLONG_EMAIL",
  TOOLONG_PASSWORD: "TOOLONG_PASSWORD",
  TOOLONG_RETYPE_PASSWORD: "TOOLONG_RETYPE_PASSWORD",
};
